name: Validação HTML

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validar-arquivos-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar o HTML-Validate
        run: npm install -g html-validate

      - name: Validar todos os arquivos HTML
        run: |
          html-validate forms.html index.html

  SAST:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Scan Externo
        run: |
          npm audit --audit-level=high || true
        continue-on-error: true 

  DAST:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instala o Server
        run: |
          npm install -g http-server
          http-server . -p 8080 & 
          sleep 5 
    
      - name: Ataque ao Server
        id: zap_scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://localhost:8080'
          json_report: true
          fail_action: false 

      - name: Coleta do Relatório DAST
        uses: actions/upload-artifact@v4
        with:
          name: ZAP-DAST-Report
          path: zap_report.json    